// 여행 액션 타입들
export const FETCH_TRAVEL_LIST = 'FETCH_TRAVEL_LIST';
export const FETCH_TRAVEL_LIST_SUCCESS = 'FETCH_TRAVEL_LIST_SUCCESS';
export const FETCH_TRAVEL_LIST_FAIL = 'FETCH_TRAVEL_LIST_FAIL';

export const INSERT_TRAVEL = 'INSERT_TRAVEL';
